# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71611286fb448991914f0a917bae2a7e8772e94cc8b61747ee617794b90536b66ed6720428dcb33d829a37bb1ed7d69792dad1b869b19968d7a83e8cd974e700

test:
  secret_key_base: 9bc7ba887ab7f18353697f6b857bb075bbd00e814cc99995730a3b5840c66fa31d25f9ef9557eb5a1ea82a59a006e38403d3a4c4ad2d1a64260eea59a7df0ea3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
